### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080/api/v1/games/title/Assassin's Creed Odyssey
###
DELETE http://localhost:8080/api/v1/games/title/

###
DELETE http://localhost:8080/api/v1/games
###
DELETE http://localhost:8080/api/v1/games/title/Assassin's Creed Odyssey
###
POST http://localhost:8080/api/v1/games
Content-Type: application/json

    {
      "title": "Prince of Persia: The Lost Crown",
      "console": "PS5",
      "status": "playing",
      "hoursPlayed": 0,
      "opinion": "",
      "startDate": "2026-02-24",
      "dateOfCompletion": ""
    }
###
POST http://localhost:8080/api/v1/games/multiple
Content-Type: application/json

[
  {
    "title": "Phoenix Wright Ace Attorney: Trials and Tribulations",
    "console": "PS4",
    "status": "completed",
    "hoursPlayed": 19,
    "opinion": "Godot is amazing, every character is, old and new. Love the last case. Amazing trilogy",
    "startDate": "2025-12-14",
    "dateOfCompletion": "2026-01-10"
  },
  {
    "title": "One Piece Odyssey: Reunion Of Memories",
    "console": "PS5",
    "status": "completed",
    "hoursPlayed": 6,
    "opinion": "Wasn't ready for some beattles, story was not engaging and all the made the game different from a turn based rpg wasnt there. not worth the full dlc price",
    "startDate": "2026-02-18",
    "dateOfCompletion": "2026-02-23"
  },
  {
    "title": "Assassin's Creed Odyssey",
    "console": "PS4",
    "status": "completed",
    "hoursPlayed": 153,
    "opinion": "Good Game, love the eagle bearer, a bit too long",
    "startDate": "2025-11-27",
    "dateOfCompletion": "2026-02-16"
  }
]

###
PUT http://localhost:8080/api/v1/games/title/Assassin's Creed Odyssey
Content-Type: application/json

{
    "title": "Assassin's Creed Odyssey",
    "console": "PS4",
    "status": "completed",
    "hoursPlayed": 150,
    "opinion": "Good Game, love the eagle bearer, a bit too long",
    "startDate": "2025-11-27",
    "dateOfCompletion": "2026-02-16"
  }