### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080/api/v1/games/status/completed

###
POST http://localhost:8080/api/v1/games
Content-Type: application/json

    {
        "title": "One Piece Odyssey: Reunion Of Memories",
        "console":"PS5",
        "status":"completed",
        "hoursPlayed":6,
        "opinion": "Wasn't ready for some beattles, story was not engaging and all the made the game different from a turn based rpg wasnt there. not worth the full dlc price",
        "startDate":"2026-02-18",
        "dateOfCompletion":"2026-02-23"
    }

